name: Lint Markdown By Yarn Install

on: [ push ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'

      - run: yarn install && yarn lint